### ISSUE TITLE
Uploads not working on Hetzner NextCloud 

### ISSUE THREAD

**Issue by johnhess** [OpenArchive/Save-app-android#333]
When using Hetzner storage, media is not uploading.  This may well be a misconfiguration on our end or Hetzners, not an app problem.  This issue covers investigating the issue finding any error messages returned to the application.

**To Reproduce**
1. Set up a WebDAV server pointed at our Hetzner instance
2. Attempt to upload

**Expected behavior**
The file is uploaded (along with meta.json, proof)

**Environment (please complete the following information):**
This occurs on both iOS and Android per Natalie.

**Additional context**
We'd like to use this provider as they charge by gigabyte rather than by user, and we tend to have more users.

**Comment by johnhess** [comment]
CC @foundscapes

**Comment by pkhivesara** [comment]
I was able to resolve this ticket. However, for me, the issue was more of a login failure. Uploads seem to work fine once you enable proofmode in the app.
Screenshot is attached.


![Image](https://user-images.githubusercontent.com/6237488/181035561-0509be1f-905f-437a-88d2-8f07ccc014e2.png)

**Comment by purvi-ranawat** [comment]
This is working fine. I am able to upload files on Hetzner NextCloud. Checked on IOS and Android both...

**Comment by johnhess** [comment]
@pkhivesara I am not able to log in on RC-9.  It looks like the login was reverted back to the hardcoded tab.digital value.

**Comment by pkhivesara** [comment]
> @pkhivesara I am not able to log in on RC-9. It looks like the login was reverted back to the hardcoded tab.digital value.

Yikes..sorry about that.. I re-reverted it back on master. Should be working now

**Comment by purvi-ranawat** [comment]
@pkhivesara : I am still not able to in into hetzner Next Cloud on RC-11. Even after entering valid URL, username and Password , it says Login failed

**Comment by purvi-ranawat** [comment]
@pkhivesara : I am still not able to login into hetzner next cloud. On clicking on login after valid credentials, it just displays 'Logging in"  and not actually login in.

Below is the screenshot : 



![Image](https://user-images.githubusercontent.com/8190141/182807894-4a38f21d-7def-4710-b356-904a16011687.png)

**Comment by purvi-ranawat** [comment]
@pkhivesara : I am now successfully able to login into the Hetzner Next Cloud. But when I click on Upload after selecting the media, the app crashes. This is happening for Hetzner NextCloud only.

Below is the video : 



https://user-images.githubusercontent.com/8190141/183085201-884fcabc-4a2f-4590-aef6-a6ab18924787.mp4

**Comment by johnhess** [comment]
FWIW @purvi-ranawat I am able to login and upload with [RC-13](https://play.google.com/apps/test/net.opendasharchive.openarchive.release/20443).  Can you check whether you're still having the issue with the linked APK?

**Comment by purvi-ranawat** [comment]
@johnhess : I am not able to access the linked apk. It is giving me "Error 404 - Not Found" message.



![Image](https://user-images.githubusercontent.com/8190141/183275038-619f8909-478a-4607-8b88-320801200de1.png)

**Comment by purvi-ranawat** [comment]
This is working fine now. I am able to upload the media successfully on Hetzner NextCloud

Environment : 

OS : Android 12
Device : Samsung Galaxy A13, Samsung Galaxy M32
Build version : 0.2.4-RC-14
