### ISSUE TITLE
Implement new webdav setup

### ISSUE THREAD

**Issue by hiromipaw** [OpenArchive/Save-app-android#434]
The new webdav setup is divided in 3 steps:

![Private Server - Log In](https://github.com/OpenArchive/Save-app-android/assets/1177650/1deb4290-bce7-41bb-87b4-b4e026b6fc8c)

![Private Server - Log In-1](https://github.com/OpenArchive/Save-app-android/assets/1177650/8e1a6e9d-d1b9-4e8f-a215-40cf7055fcc1)

![Private Server - Success](https://github.com/OpenArchive/Save-app-android/assets/1177650/9cdf6b0c-04f3-4edf-8cb1-aa3017b76210)

Typography for title and description:
```
font-family: Montserrat;
font-size: 14px;
font-style: italic;
font-weight: 700;
line-height: 16px;
letter-spacing: 0.01em;
text-align: left;

font-family: Montserrat;
font-size: 14px;
font-weight: 500;
line-height: 16px;
letter-spacing: 0.01em;
text-align: left;
```

Form typography:
```
/* Server Info */

width: 331px;
height: 16px;

font-family: 'Montserrat';
font-style: normal;
font-weight: 600;
font-size: 14px;
line-height: 16px;
/* identical to box height, or 114% */
letter-spacing: 0.01em;

/* White */
color: #FFFFFF;


/* Inside auto layout */
flex: none;
order: 0;
align-self: stretch;
flex-grow: 0;

/* ↪ Label */

width: 291px;
height: 24px;

font-family: 'Montserrat';
font-style: normal;
font-weight: 400;
font-size: 13px;
line-height: 18px;
/* or 138% */
display: flex;
align-items: center;

/* White */
color: #FFFFFF;
```

Figma:
https://www.figma.com/file/MngzLdtPsEmvEsUPKsbmE8/Save-App-2.0

Image:
![Group 431](https://github.com/OpenArchive/Save-app-android/assets/1177650/87a13a20-ebf9-48a8-bec2-2b33ef689af9)

**Comment by tladesignz** [comment]
@uniqx, since the activity is the same as in  #447, I already worked towards this, too.
However, you're definitely the one who's more knowledgable around Android styling, so I let you the progress header and the last scene and general brushing and making sure that colors work in dark mode... :-)

**Comment by uniqx** [comment]
Should be fixed, by the 0.3.0-alpha7 release the upload chunking part. I think we cant to add that later on, right?

**Comment by tladesignz** [comment]
@purvi-ranawat: This should already be released in the public alpha!

**Comment by purvi-ranawat** [comment]
@uniqx / @tladesignz : The issue is still not resolved.

"Use Upload Chunking"option is still not displayed on Private (Webdav) server screen.

Below is the screenshot : 

![image](https://github.com/OpenArchive/Save-app-android/assets/8190141/c284fd9f-092a-4d86-885b-fe0340eace4c)

Environment : 

OS : Android 11, Android 13
Device : Samsung Galaxy A13, Samsung Galaxy A70
Build version : 0.3.0-alpha8



Note : In the below image, the error message mentioned is : "Create a username without a special symbol" . How do I get this error? as on entering the username with the special characters, it says to enter valid username or password.

![image](https://github.com/OpenArchive/Save-app-android/assets/8190141/5f0c020a-6134-4369-b7e7-10cefa2923e6)

**Comment by tladesignz** [comment]
@purvi-ranawat, the upload chunking change will be contained in version 0.3.0-alpha9, build 20538.

**Comment by foundscapes** [comment]
@tladesignz are these issues resolved now?

**Comment by foundscapes** [comment]
@purvi-ranawat please test to see if resolved, ty

**Comment by purvi-ranawat** [comment]
@foundscapes / @tladesignz : upload chunking change is now implemented in 0.3.0-beta3 version. But I am still not getting the error message given in the screenshot below : 



![Image](https://github.com/OpenArchive/Save-app-android/assets/8190141/269137d7-319c-444b-9959-546213a103e7)

Note : In the above image, the error message mentioned is : "Create a username without a special symbol" . How do I get this error? as on entering the username with the special characters, it says to enter valid username or password.

**Comment by tladesignz** [comment]
> Note : In the above image, the error message mentioned is : "Create a username without a special symbol" . How do I get this error? as on entering the username with the special characters, it says to enter valid username or password.

This error message will never exist, as it was just a uninformed example of the designer.

There is no reason to keep people from using special characters in their usernames. I can imagine Chinese or Arab users wanting a username in their scripture. I don't see a problem in mathematical symbols as usernames. What exactly is a "special character" anyway? That can mean a lot of different things to different people.

Besides that, this form is not for registering an account, but using an already existing account. It is not on us to decide, how a username on a specific server is allowed to look.


Another note on the design: We're not going to replicate the exact error behavour provided in this design. Instead, we're using the Android-provided standard way of displaying errors. Too much effort, for too little gain to implement our own look & feel. (Also because of accessibility!)


If that's the last thing you found, I guess we're good now?

Thank you, @purvi-ranawat, for your diligence!

I'll close this now. If you stumble upon other problems, feel free to reopen!
