### ISSUE TITLE
Next button overlaps pw field for Internet Archive login 

### ISSUE THREAD

**Issue by ceylana** [OpenArchive/Save-app-android#468]
**Describe the bug**
Next and back buttons overlaps  with description fields.

**To Reproduce**
1. Go to Internet Archive Login
2. Click on  "Access Key" or "Secret Key" text field
3. Next and back buttons overlap text

**Expected behavior**
need more padding

**Screenshots**
![Uploading signal-2023-08-22-161954.jpeg…]()
ha5

**Environment (please complete the following information):**
 - OS version: Android
 - Device: Samsung Galaxy S10
 - App Version 0.3.0-alp

**Additional context**

**Comment by foundscapes** [comment]
@purvi-ranawat can you verify this is fixed? it worked for me in alpha8 - ty!

**Comment by purvi-ranawat** [comment]
@foundscapes : The issue still exists for me on 0.3.0-alpha8 release

Below is the screenshot : 

![image](https://github.com/OpenArchive/Save-app-android/assets/8190141/30f77786-7568-4a27-a11a-72378332137f)


OS : Android 11, Android 13
Device : Samsung Galaxy A13, Samsung Galaxy A70
build Version : 0.3.0-alpha8

**Comment by foundscapes** [comment]
@purvi-ranawat can you test again with beta1, it's still working for me, thanks!

**Comment by foundscapes** [comment]
@purvi-ranawat this isn't showing up for Alex anymore (it was never an issue for me), can you please test this on beta5 and then close if it's fixed for you.

**Comment by foundscapes** [comment]
@vanichitkara please test and close if it's working for you, ty!

**Comment by purvi-ranawat** [comment]
@foundscapes " This is working fine for me now

Environment : 
OS : Android 11, Android 13
Device : Samsung Galaxy A13, Samsung Galaxy A70
Build Version : 0.3.0-beta6

**Comment by foundscapes** [comment]
great, thanks @purvi-ranawat !
